### PR TITLE
34: Adding support for JSON files

### PR DESCRIPTION
**Pull request by anands**
- [x] Does all of your new or changed code have unit tests?
- [x] Is overall unit test statement coverage still above 85%?
- [x] Is code style linting passing with `npm run lint`?
- [x] Is the related GitHub issue number included in your branch name? ex branch name: `fix/12-some-bug`
- [x] Is the related GitHub issue number included in your pull request title? example PR title: "12 - Fixes some bug"
- [x] Is documentation still up to date after your change?

At times I have tests in JSON files, adding support for JSON files out of the box would surely be helpful. Changes at the YAML level are not necessary as the [js-yaml schema supports JSON in the core schema itself](https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/schema/core.js#L16).

### CODE REVIEW

**Comment by ejfrancis** [comment]
Could you please create an accompanying issue that lays out the problem that this is solving, and include that issue number in your branch name? I'm not familiar w/JSON in YAML so any examples would be great. Thanks!

**Comment by anands** [comment]
@ejfrancis I have created the issue #34 . And the example is already present in the PR: here it is: https://github.com/intuit/judo/pull/33/files#diff-b95cea12fb199522ee6a03ea959033f6

**Comment by ejfrancis** [comment]
Great, thanks for making the issue. I think this all looks great, only other thing is could you add an example right to the README? I'm thinking after the "Complete YAML Example" maybe you could add "Equivalent complete JSON Example" with the JSON equivalent of the YAML example that explains JSON is also possible

**Comment by anands** [comment]
@efrancis I have added the example in README

**Pull request merged**
